### ISSUE TITLE
Solving Algorithm Doesnt Work

### ISSUE THREAD

**Issue by ethandeguire** [slammayjammay/rubiks-cube-solver#1]
The algorithm used for solving works inconsistently, has it been properly tested?

**Comment by slammayjammay** [comment]
Holy moly I didn't realize the tests are completely botched. I'll get them working again but I'm pretty sure that when they were running properly they were all passing...can you give a reproducible example of it failing?

**Comment by ethandeguire** [comment]
I can work on it later, but I don't believe that even the example solve in
the readme/on the github page was working, it got close to a solve, but
didnt complete. I could be doing something wrong

**Comment by slammayjammay** [comment]
I got the tests working again and they all pass. The example solve in the readme works as well. I'm just noticing now that I forgot to make a note in the readme that notations are case-sensitive. Could be that?

**Comment by ethandeguire** [comment]
There’s a good chance it was the case sensitivities, I noticed sometimes it ouputs a lowercase ‘d’ and othertimes uppercase. not sure what’s up with that.

**Comment by slammayjammay** [comment]
Lowercase notation is separate from uppercase notation, they indicate double-layer turns. You can see examples [here](https://ruwix.com/the-rubiks-cube/notation/advanced/).

**Comment by slammayjammay** [comment]
Closing.
